In [10]:
import numpy as np
import pandas as pd

df=pd.read_csv('dataset2.csv')
#df=pd.read_csv('tweet.csv')

df.head()

Unnamed: 0                                              tweet      label  \
0           0  ya orospu cocuklari hepiniz niye ayni anda yaz...     nefret   
1           1  ciddiye alan tüm dünyanın beynini sileyim.. iş...  saldırgan   
2           2  kayıtlı i̇stihdama geçiş programına göre (?) ş...    hiçbiri   
3           3  hastaneye git suriyeli. ptt ye git suriyeli. p...     nefret   
4           4               cölesi bitmiş suriyeli gibiyim bugün    hiçbiri   

   label2  
0       1  
1       2  
2       0  
3       1  
4       0

In [11]:
tweet=df['tweet']
y=df['label'].values


In [12]:
print(tweet)

0        ya orospu cocuklari hepiniz niye ayni anda yaz...
1        ciddiye alan tüm dünyanın beynini sileyim.. iş...
2        kayıtlı i̇stihdama geçiş programına göre (?) ş...
3        hastaneye git suriyeli. ptt ye git suriyeli. p...
4                     cölesi bitmiş suriyeli gibiyim bugün
                               ...                        
11217    bu sadece kadın erkek meselesi mi hayır iyi in...
11218    eşcinsel genin olmadığına dair bilimsel çalışm...
11219    eşcinsel çiftin düğün fotoğrafları viral oldu ...
11220    kral şakir necati karakteri... türk dizilerind...
11221    ulan maçı unutayım kafam dağılsın diye netflix...
Name: tweet, Length: 11222, dtype: object


In [13]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
X=vectorizer.fit_transform(tweet)

print(X.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0,shuffle=True)

print("trainign data shape:",X_train.shape)
print("testing data shape:",X_test.shape)

trainign data shape: (8977, 56234)
testing data shape: (2245, 56234)


In [15]:
from sklearn.neighbors import KNeighborsClassifier
knn_model=KNeighborsClassifier(n_neighbors=3)
knn_model.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [16]:
predictions=knn_model.predict(X_test)
from sklearn import metrics
print(metrics.confusion_matrix(y_test,predictions))

[[1554  109    4]
 [ 294  245    2]
 [  25   10    2]]


In [17]:
print(metrics.classification_report(y_test,predictions))

              precision    recall  f1-score   support

     hiçbiri       0.83      0.93      0.88      1667
      nefret       0.67      0.45      0.54       541
   saldırgan       0.25      0.05      0.09        37

    accuracy                           0.80      2245
   macro avg       0.58      0.48      0.50      2245
weighted avg       0.78      0.80      0.78      2245



In [18]:
print(metrics.accuracy_score(y_test,predictions))

0.8022271714922049


In [19]:
print(knn_model.score(X_train,y_train))

0.8806951097248524


In [ ]:
sent_test_vector=vectorizer.transform(["****"])
print(sent_test_vector)

y_pred=knn_model.predict(sent_test_vector.toarray())
print(y_pred)